### ISSUE TITLE
Suggestion for a packed version

### ISSUE THREAD

**Issue by LenniDev** [Hephaestus-Dev/SAX#10]
Can you provide a packed version as "*.jar" file that I can put in the /mods/ folder because I cant build this with gradlew.
Everytime I try to build it I get:

Could not resolve all files for configuration ':modCompileClasspath'.
Could not find me.jellysquid.mods:lithium:0.6.3-SNAPSHOT.
Searched in the following locations:
- https://hephaestus.dev/release/me/jellysquid/mods/lithium/0.6.3-SNAPSHOT/maven-metadata.xml
- https://hephaestus.dev/release/me/jellysquid/mods/lithium/0.6.3-SNAPSHOT/lithium-0.6.3-SNAPSHOT.pom
I use Linux Ubuntu 20 with Gradle 5.5.1

**Comment by Haven-King** [comment]
It is available on [Modrinth ](https://modrinth.com/mod/sax) and [the releases tab](https://github.com/Haven-King/SAX/releases/tag/1.0.1).

**Comment by LenniDev** [comment]
> It is available on [Modrinth ](https://modrinth.com/mod/sax) and [the releases tab](https://github.com/Haven-King/SAX/releases/tag/1.0.1).

Ok thank you very much for help.
