### ISSUE TITLE
Nether still isn't working as expected

### ISSUE THREAD

**Issue by matthewperiut** [Hephaestus-Dev/SAX#5]
I believe the config file wasn't the culprit considering that I had modified it previously in 0.1.0. For some reason, the nether just doesn't like the mod.

Here's what I've got:
![2020-12-23_02 08 25](https://user-images.githubusercontent.com/18296791/102970634-e370d200-44c5-11eb-8dfd-894f851b7a06.png)
![ModsFolder](https://user-images.githubusercontent.com/18296791/102970694-fbe0ec80-44c5-11eb-888c-ff988bb80925.PNG)

**Comment by Haven-King** [comment]
Old issue.
