### ISSUE TITLE
"Exception ticking world" happening sporadically when loading specific parts of the world

### ISSUE THREAD

**Issue by bleeper913** [Hephaestus-Dev/SAX#6]
Really not sure I understand how SAX is causing this, but it definitely is. I downloaded a backup of a server, deleted all mods and datapacks except SAX and Fabric API. 

Whenever a specific area is loaded, whether by a player or an entity (like throwing an item through a nether portal), the game crashes throwing an "exception ticking world". 

I'm not sure what to gleam from the crash log, so I wanted to leave it here in hopes someone else could help me make sense of what happened.

[https://pastebin.com/Z5ZDDkrr](https://pastebin.com/Z5ZDDkrr)

**Comment by Haven-King** [comment]
No longer an issue in the current version.
