### ISSUE TITLE
Massive server lag

### ISSUE THREAD

**Issue by srnyx** [Hephaestus-Dev/SAX#9]
My server experiences a ton of lag when the mod is installed.
_I've only heard this from the players (and console being like "Is the server overloading?") and haven't experienced it first-hand._

**Spark reports:**
With mod: https://spark.lucko.me/#Xr3SuDZDek
Without mod: https://spark.lucko.me/#afnqHSNfYN

I think it may be some sort of incompatibility with Lithium (I dug really deep into the with mod Spark report and found this: `net.minecraft.class_1937.getChunkLithium()`).

**Comment by DVIcable** [comment]
I also experienced this issue, the server runs fine until anyone joins, then the cpu usage spikes significantly.

**Comment by srnyx** [comment]
> I also experienced this issue, the server runs fine until anyone joins, then the cpu usage spikes significantly.

Yeah same. Only happens when someone joins

**Comment by LenniDev** [comment]
Can you provide a packed version as "*.jar" file that I can put in the /mods/ folder because I cant build this with gradlew.
Everytime I try to build it I get:
> Could not resolve all files for configuration ':modCompileClasspath'.
   > Could not find me.jellysquid.mods:lithium:0.6.3-SNAPSHOT.
     Searched in the following locations:
       - https://hephaestus.dev/release/me/jellysquid/mods/lithium/0.6.3-SNAPSHOT/maven-metadata.xml
       - https://hephaestus.dev/release/me/jellysquid/mods/lithium/0.6.3-SNAPSHOT/lithium-0.6.3-SNAPSHOT.pom
I use Linux Ubuntu 20 with Gradle 5.5.1

**Comment by Haven-King** [comment]
You could reduce the chunk distance in the config file. I will add more performance tuning/throttling config options in the future.

**Comment by LenniDev** [comment]
I have two Questions,
firstly I have a similar problem. When 3 players join, the server lags and at 4 players, the server crashes. The MC server runs on Debian with 3 vCores and 4 GB RAM. I'll append the logs below:

https://gist.github.com/LenniDev/274ad3c33bb5b8fd9795bc30b26e9f97

And secondly I wanted to ask should I increase RAM or the Cores when I whant to run this mod.

**Comment by srnyx** [comment]
> I have two Questions,
> firstly I have a similar problem. When 3 players join, the server lags and at 4 players, the server crashes. The MC server runs on Debian with 3 vCores and 4 GB RAM. I'll append the logs below:
> 
> https://gist.github.com/LenniDev/274ad3c33bb5b8fd9795bc30b26e9f97
> 
> And secondly I wanted to ask should I increase RAM or the Cores when I whant to run this mod.

I run 8 GB and it lags with 1 player with around 100 mods installed.

**Comment by LenniDev** [comment]
> > I have two Questions,
> > firstly I have a similar problem. When 3 players join, the server lags and at 4 players, the server crashes. The MC server runs on Debian with 3 vCores and 4 GB RAM. I'll append the logs below:
> > https://gist.github.com/LenniDev/274ad3c33bb5b8fd9795bc30b26e9f97
> > And secondly I wanted to ask should I increase RAM or the Cores when I whant to run this mod.
> 
> I run 8 GB and it lags with 1 player with around 100 mods installed.

I run only with phosphor and lithium.

**Comment by Haven-King** [comment]
Please download the latest version from either [Modrinth ](https://modrinth.com/mod/sax/version/uKjtpldv)or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/simple-anti-x-ray/files/3248410), play with the new performance options, and let me know if the problems persist!
